package edu.avanzada.taller2.vista;

import edu.avanzada.taller2.control.ControlPrincipal;
import javax.swing.JTextField;


/**
 *
 * @author Personal
 */
public class CrearEquipo  extends javax.swing.JFrame {

    private ControlPrincipal control;

    /**
     * Creates new form CrearEquipo
     */
    public CrearEquipo(ControlPrincipal aThis) {
        initComponents();
        control = aThis;
        //setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public void resetearCamposCrearEquipo() {
        TextoNombreEquipo.setText("");

        Nombre.setText("");
        Cedula.setText("");
        Edad.setText("");
        AñosExp.setText("");

        Nombre1.setText("");
        Cedula1.setText("");
        Edad1.setText("");

        Nombre2.setText("");
        Cedula2.setText("");
        Edad2.setText("");

        Nombre3.setText("");
        Cedula3.setText("");
        Edad3.setText("");

        Nombre4.setText("");
        Cedula4.setText("");
        Edad4.setText("");

        Nombre5.setText("");
        Cedula5.setText("");
        Edad5.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Equipo = new javax.swing.JTabbedPane();
        NombreEquipo = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        BotonRegistrar = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TextoNombreEquipo = new javax.swing.JTextField();
        Capitan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        AñosExp = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jugador1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JTextField();
        Edad1 = new javax.swing.JTextField();
        Cedula1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Jugador2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JTextField();
        Edad2 = new javax.swing.JTextField();
        Cedula2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Jugador3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JTextField();
        Edad3 = new javax.swing.JTextField();
        Cedula3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Jugador4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Nombre4 = new javax.swing.JTextField();
        Edad4 = new javax.swing.JTextField();
        Cedula4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Jugador5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Nombre5 = new javax.swing.JTextField();
        Edad5 = new javax.swing.JTextField();
        Cedula5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Equipo.setBackground(new java.awt.Color(153, 153, 255));

        NombreEquipo.setBackground(new java.awt.Color(204, 204, 255));

        BotonSalir.setBackground(new java.awt.Color(186, 186, 249));
        BotonSalir.setText("Salir");
        BotonSalir.setBorder(null);

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/avanzada/taller2/vista/ranaa.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 153));
        jLabel26.setText("Nombre Equipo");

        TextoNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NombreEquipoLayout = new javax.swing.GroupLayout(NombreEquipo);
        NombreEquipo.setLayout(NombreEquipoLayout);
        NombreEquipoLayout.setHorizontalGroup(
            NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                .addGroup(NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NombreEquipoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NombreEquipoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BotonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(BotonRegistrar)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                        .addComponent(TextoNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        NombreEquipoLayout.setVerticalGroup(
            NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreEquipoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addGroup(NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(NombreEquipoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextoNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(NombreEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NombreEquipoLayout.createSequentialGroup()
                                .addComponent(BotonRegistrar)
                                .addGap(18, 18, 18))))))
        );

        Equipo.addTab("Nombre E", NombreEquipo);

        Capitan.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Edad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cedula");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Capitan");

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        AñosExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñosExpActionPerformed(evt);
            }
        });

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Años Exp");

        javax.swing.GroupLayout CapitanLayout = new javax.swing.GroupLayout(Capitan);
        Capitan.setLayout(CapitanLayout);
        CapitanLayout.setHorizontalGroup(
            CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapitanLayout.createSequentialGroup()
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapitanLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapitanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CapitanLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(Edad)
                            .addComponent(Nombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapitanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AñosExp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CapitanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(132, 132, 132))
        );
        CapitanLayout.setVerticalGroup(
            CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CapitanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(CapitanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñosExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Equipo.addTab("Capitan", Capitan);

        Jugador1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Edad");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cedula");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nombre");

        Edad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edad1ActionPerformed(evt);
            }
        });

        Cedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Jugador 1 ");

        javax.swing.GroupLayout Jugador1Layout = new javax.swing.GroupLayout(Jugador1);
        Jugador1.setLayout(Jugador1Layout);
        Jugador1Layout.setHorizontalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(Edad1)
                    .addComponent(Cedula1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Jugador1Layout.setVerticalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Equipo.addTab("J. 1", Jugador1);

        Jugador2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Cedula");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nombre");

        Edad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edad2ActionPerformed(evt);
            }
        });

        Cedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Jugador 2 ");

        javax.swing.GroupLayout Jugador2Layout = new javax.swing.GroupLayout(Jugador2);
        Jugador2.setLayout(Jugador2Layout);
        Jugador2Layout.setHorizontalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(Nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(Edad2)
                    .addComponent(Cedula2))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Jugador2Layout.setVerticalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addGroup(Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Cedula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Equipo.addTab("J. 2", Jugador2);

        Jugador3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Edad");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Cedula");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Nombre");

        Edad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edad3ActionPerformed(evt);
            }
        });

        Cedula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Jugador 3 ");

        javax.swing.GroupLayout Jugador3Layout = new javax.swing.GroupLayout(Jugador3);
        Jugador3.setLayout(Jugador3Layout);
        Jugador3Layout.setHorizontalGroup(
            Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(26, 26, 26)
                .addGroup(Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(Nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(Edad3)
                    .addComponent(Cedula3))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Jugador3Layout.setVerticalGroup(
            Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17)
                .addGap(33, 33, 33)
                .addGroup(Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Edad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Cedula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Equipo.addTab("J.3", Jugador3);

        Jugador4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Edad");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Cedula");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Nombre");

        Edad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edad4ActionPerformed(evt);
            }
        });

        Cedula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula4ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Jugador 4");

        javax.swing.GroupLayout Jugador4Layout = new javax.swing.GroupLayout(Jugador4);
        Jugador4.setLayout(Jugador4Layout);
        Jugador4Layout.setHorizontalGroup(
            Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(26, 26, 26)
                .addGroup(Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21)
                    .addComponent(Nombre4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(Edad4)
                    .addComponent(Cedula4))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Jugador4Layout.setVerticalGroup(
            Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addGap(33, 33, 33)
                .addGroup(Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Edad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Cedula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Equipo.addTab("J. 4", Jugador4);

        Jugador5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Edad");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Cedula");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Nombre");

        Edad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edad5ActionPerformed(evt);
            }
        });

        Cedula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cedula5ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 153));
        jLabel25.setText("Jugador 5 ");

        javax.swing.GroupLayout Jugador5Layout = new javax.swing.GroupLayout(Jugador5);
        Jugador5.setLayout(Jugador5Layout);
        Jugador5Layout.setHorizontalGroup(
            Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addGap(26, 26, 26)
                .addGroup(Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25)
                    .addComponent(Edad5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(Nombre5)
                    .addComponent(Cedula5))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        Jugador5Layout.setVerticalGroup(
            Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addGap(33, 33, 33)
                .addGroup(Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Edad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Jugador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Cedula5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        Equipo.addTab("J.5", Jugador5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Equipo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void TextoNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreEquipoActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void AñosExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñosExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñosExpActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void Edad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad1ActionPerformed

    private void Cedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula1ActionPerformed

    private void Edad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad2ActionPerformed

    private void Cedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula2ActionPerformed

    private void Edad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad3ActionPerformed

    private void Cedula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula3ActionPerformed

    private void Edad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad4ActionPerformed

    private void Cedula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula4ActionPerformed

    private void Edad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edad5ActionPerformed

    private void Cedula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cedula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cedula5ActionPerformed

    public JTextField cargarNombreEquipo() {
        return TextoNombreEquipo;
    }
    public JTextField cargarNombre() {
        return Nombre;
    }

    public JTextField cargarEdad() {
        return Edad;
    }

    public JTextField cargarCedula() {
        return Cedula;
    }

    public JTextField cargarAñosExp() {
        return AñosExp;
    }

    public JTextField cargarNombre1() {
        return Nombre1;
    }

    public JTextField cargarEdad1() {
        return Edad1;
    }

    public JTextField cargarCedula1() {
        return Cedula1;
    }

    public JTextField cargarNombre2() {
        return Nombre2;
    }

    public JTextField cargarEdad2() {
        return Edad2;
    }

    public JTextField cargarCedula2() {
        return Cedula2;
    }

    public JTextField cargarNombre3() {
        return Nombre3;
    }

    public JTextField cargarEdad3() {
        return Edad3;
    }

    public JTextField cargarCedula3() {
        return Cedula3;
    }

    public JTextField cargarNombre4() {
        return Nombre4;
    }

    public JTextField cargarEdad4() {
        return Edad4;
    }

    public JTextField cargarCedula4() {
        return Cedula4;
    }

    public JTextField cargarNombre5() {
        return Nombre5;
    }

    public JTextField cargarEdad5() {
        return Edad5;
    }

    public JTextField cargarCedula5() {
        return Cedula5;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField AñosExp;
    public javax.swing.JButton BotonRegistrar;
    public javax.swing.JButton BotonSalir;
    public javax.swing.JButton BotonVolver;
    public javax.swing.JPanel Capitan;
    public javax.swing.JTextField Cedula;
    public javax.swing.JTextField Cedula1;
    public javax.swing.JTextField Cedula2;
    public javax.swing.JTextField Cedula3;
    public javax.swing.JTextField Cedula4;
    public javax.swing.JTextField Cedula5;
    public javax.swing.JTextField Edad;
    public javax.swing.JTextField Edad1;
    public javax.swing.JTextField Edad2;
    public javax.swing.JTextField Edad3;
    public javax.swing.JTextField Edad4;
    public javax.swing.JTextField Edad5;
    public javax.swing.JTabbedPane Equipo;
    public javax.swing.JPanel Jugador1;
    public javax.swing.JPanel Jugador2;
    public javax.swing.JPanel Jugador3;
    public javax.swing.JPanel Jugador4;
    public javax.swing.JPanel Jugador5;
    public javax.swing.JTextField Nombre;
    public javax.swing.JTextField Nombre1;
    public javax.swing.JTextField Nombre2;
    public javax.swing.JTextField Nombre3;
    public javax.swing.JTextField Nombre4;
    public javax.swing.JTextField Nombre5;
    public javax.swing.JPanel NombreEquipo;
    public javax.swing.JTextField TextoNombreEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
